version: '3'

networks:
  mongodb_network:
    driver: bridge
  rabbitmq_network:
    driver: bridge
  api_network:
    driver: bridge

services:
  mongodb:
    image: mongo:3.4
    container_name: MongoDB
    networks:
      - mongodb_network

  rabbitmq:
    build: ./rabbitmq
    image: claclacla/rabbitmq
    container_name: RabbitMQ
    networks:
      - rabbitmq_network

  mongo-seed:
    build: ./mongo-seed
    image: claclacla/mongo-seed
    container_name: MongoSeed
    networks:
      - mongodb_network
    depends_on:
      - mongodb
    command: [
      "mongoimport --host mongodb --port 27017 --db appDB --type json --file teachers.json --jsonArray"
    ]

  celery:
    build: ./celery
    image: claclacla/celery
    container_name: Celery
    environment:
      - SMTP_ADDRESS=smtp.mock-address.com
      - SMTP_PORT=25
      - SMTP_USERNAME=username
      - SMTP_PASSWORD=password
    networks:
      - rabbitmq_network

  flask-api-server:
    build: ./flask-api-server
    image: claclacla/flask-api-server
    container_name: FlaskAPIServer
    volumes:
      - "${APP_FOLDER}/src:/usr/src/app"
    networks:
      - mongodb_network
      - rabbitmq_network
      - api_network
    ports: 
      - "5000:5000"

  tests:
    build: ./tests
    image: claclacla/tests
    container_name: Tests
    volumes:
      - "${APP_FOLDER}/tests:/usr/src/app"
    networks:
      - api_network