version: '3'

networks:
  mongodb_network:
    driver: bridge
  rabbitmq_network:
    driver: bridge

services:
  mongodb:
    image: mongo:3.4
    container_name: MongoDB
    networks:
      - mongodb_network

  rabbitmq:
    build: ./rabbitmq
    image: claclacla/rabbitmq
    container_name: RabbitMQ
    networks:
      - rabbitmq_network

  mongo-seed:
    build: ./mongo-seed
    image: claclacla/mongo-seed
    container_name: MongoSeed
    networks:
      - mongodb_network
    depends_on:
      - mongodb
    command: [
      "mongoimport --host mongodb --port 27017 --db appDB --type json --file teachers.json --jsonArray"
    ]

  flask-api-server:
    build: ./flask-api-server
    image: claclacla/flask-api-server
    container_name: FlaskAPIServer
    volumes:
      - "${APP_FOLDER}:/usr/src/app"
    networks:
      - mongodb_network
      - rabbitmq_network
    ports: 
      - "5000:5000"