version: '3'

networks:
  mongodb_network:
    driver: bridge

services:
  mongodb:
    image: mongo:3.4
    container_name: MongoDB
    networks:
      - mongodb_network

  flask-api-server:
    build: ./flask-api-server
    image: claclacla/flask-api-server
    container_name: FlaskAPIServer
    volumes:
      - "${APP_FOLDER}:/usr/src/app"
    networks:
      - mongodb_network
    ports: 
      - "5000:5000"